2025-09-14T07:50:53.396Z [generate-image] SDK ERROR: got status: 403 Forbidden. {"error":{"message":"exception parsing response","code":403,"status":"Forbidden"}}
ClientError: got status: 403 Forbidden. {"error":{"message":"exception parsing response","code":403,"status":"Forbidden"}}
    at throwErrorIfNotOK (C:\cointistreact\node_modules\@google\genai\dist\node\index.js:9186:33)
    at C:\cointistreact\node_modules\@google\genai\dist\node\index.js:9009:19
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Models.generateContentStream (C:\cointistreact\node_modules\@google\genai\dist\node\index.js:7794:20)
    at async n (C:\cointistreact\.next\server\pages\api\generate-image.js:7:23)
    at async ts (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.prod.js:1:100928)
    at async to.render (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.prod.js:1:101643)
    at async Module.t (C:\cointistreact\.next\server\pages\api\generate-image.js:16:1743)
    at async DevServer.runApi (C:\cointistreact\node_modules\next\dist\server\next-server.js:766:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\cointistreact\node_modules\next\dist\server\next-server.js:390:37)
    at async DevServer.handleRequestImpl (C:\cointistreact\node_modules\next\dist\server\base-server.js:916:17)
    at async C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:399:20
    at async Span.traceAsyncFn (C:\cointistreact\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:395:24)
    at async invokeRender (C:\cointistreact\node_modules\next\dist\server\lib\router-server.js:240:21)

2025-09-14T08:08:17.411Z [generate-image] ERROR: Responses API image parse failed and Images API fallback also failed: fetch failed
Error: Responses API image parse failed and Images API fallback also failed: fetch failed
    at generateArticleImage (webpack-internal:///(api-node)/./scripts/generate-article-image.js:469:15)
    at async handler (webpack-internal:///(api-node)/./pages/api/generate-image.ts:221:16)
    at async apiResolver (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:4425)
    at async PagesAPIRouteModule.render (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:5955)
    at async Module.handler (webpack-internal:///(api-node)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fgenerate-image&preferredRegion=&absolutePagePath=.%2Fpages%5Capi%5Cgenerate-image.ts&middlewareConfigBase64=e30%3D!:115:13)
    at async DevServer.runApi (C:\cointistreact\node_modules\next\dist\server\next-server.js:766:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\cointistreact\node_modules\next\dist\server\next-server.js:390:37)
    at async DevServer.handleRequestImpl (C:\cointistreact\node_modules\next\dist\server\base-server.js:916:17)
    at async C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:399:20
    at async Span.traceAsyncFn (C:\cointistreact\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:395:24)
    at async invokeRender (C:\cointistreact\node_modules\next\dist\server\lib\router-server.js:240:21)
    at async handleRequest (C:\cointistreact\node_modules\next\dist\server\lib\router-server.js:437:24)
    at async requestHandlerImpl (C:\cointistreact\node_modules\next\dist\server\lib\router-server.js:485:13)
    at async Server.requestListener (C:\cointistreact\node_modules\next\dist\server\lib\start-server.js:226:13)

2025-09-14T08:54:59.951Z [generate-image] ERROR: fetch failed
TypeError: fetch failed
    at node:internal/deps/undici/undici:13510:13
    at async callImagesAPI (webpack-internal:///(api-node)/./scripts/generate-article-image.js:48:15)
    at async generateArticleImage (webpack-internal:///(api-node)/./scripts/generate-article-image.js:481:16)
    at async handler (webpack-internal:///(api-node)/./pages/api/generate-image.ts:221:16)
    at async apiResolver (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:4425)
    at async PagesAPIRouteModule.render (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:5955)
    at async Module.handler (webpack-internal:///(api-node)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fgenerate-image&preferredRegion=&absolutePagePath=.%2Fpages%5Capi%5Cgenerate-image.ts&middlewareConfigBase64=e30%3D!:115:13)
    at async DevServer.runApi (C:\cointistreact\node_modules\next\dist\server\next-server.js:766:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\cointistreact\node_modules\next\dist\server\next-server.js:390:37)
    at async DevServer.handleRequestImpl (C:\cointistreact\node_modules\next\dist\server\base-server.js:916:17)
    at async C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:399:20
    at async Span.traceAsyncFn (C:\cointistreact\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:395:24)
    at async invokeRender (C:\cointistreact\node_modules\next\dist\server\lib\router-server.js:240:21)
    at async handleRequest (C:\cointistreact\node_modules\next\dist\server\lib\router-server.js:437:24)

2025-09-14T08:58:15.540Z [generate-image] ERROR: This operation was aborted
AbortError: This operation was aborted
    at node:internal/deps/undici/undici:13510:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchWithRetry (webpack-internal:///(api-node)/./scripts/generate-article-image.js:27:19)
    at async callImagesAPI (webpack-internal:///(api-node)/./scripts/generate-article-image.js:75:15)
    at async generateArticleImage (webpack-internal:///(api-node)/./scripts/generate-article-image.js:508:16)
    at async handler (webpack-internal:///(api-node)/./pages/api/generate-image.ts:221:16)
    at async apiResolver (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:4425)
    at async PagesAPIRouteModule.render (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:5955)
    at async Module.handler (webpack-internal:///(api-node)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fgenerate-image&preferredRegion=&absolutePagePath=.%2Fpages%5Capi%5Cgenerate-image.ts&middlewareConfigBase64=e30%3D!:115:13)
    at async DevServer.runApi (C:\cointistreact\node_modules\next\dist\server\next-server.js:766:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\cointistreact\node_modules\next\dist\server\next-server.js:390:37)
    at async DevServer.handleRequestImpl (C:\cointistreact\node_modules\next\dist\server\base-server.js:916:17)
    at async C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:399:20
    at async Span.traceAsyncFn (C:\cointistreact\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:395:24)

2025-09-14T11:42:55.549Z [generate-image] ERROR: This operation was aborted
AbortError: This operation was aborted
    at node:internal/deps/undici/undici:13510:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchWithTimeout (webpack-internal:///(api-node)/./scripts/generate-article-image.js:34:15)
    at async callImagesAPI (webpack-internal:///(api-node)/./scripts/generate-article-image.js:68:15)
    at async generateArticleImage (webpack-internal:///(api-node)/./scripts/generate-article-image.js:535:16)
    at async handler (webpack-internal:///(api-node)/./pages/api/generate-image.ts:346:16)
    at async apiResolver (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:4425)
    at async PagesAPIRouteModule.render (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:5955)
    at async Module.handler (webpack-internal:///(api-node)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fgenerate-image&preferredRegion=&absolutePagePath=.%2Fpages%5Capi%5Cgenerate-image.ts&middlewareConfigBase64=e30%3D!:115:13)
    at async DevServer.runApi (C:\cointistreact\node_modules\next\dist\server\next-server.js:766:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\cointistreact\node_modules\next\dist\server\next-server.js:390:37)
    at async DevServer.handleRequestImpl (C:\cointistreact\node_modules\next\dist\server\base-server.js:916:17)
    at async C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:399:20
    at async Span.traceAsyncFn (C:\cointistreact\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:395:24)

2025-09-14T11:45:07.620Z [generate-image] ERROR: This operation was aborted
AbortError: This operation was aborted
    at node:internal/deps/undici/undici:13510:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchWithTimeout (webpack-internal:///(api-node)/./scripts/generate-article-image.js:34:15)
    at async callImagesAPI (webpack-internal:///(api-node)/./scripts/generate-article-image.js:68:15)
    at async generateArticleImage (webpack-internal:///(api-node)/./scripts/generate-article-image.js:535:16)
    at async handler (webpack-internal:///(api-node)/./pages/api/generate-image.ts:346:16)
    at async apiResolver (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:4425)
    at async PagesAPIRouteModule.render (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:5955)
    at async Module.handler (webpack-internal:///(api-node)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fgenerate-image&preferredRegion=&absolutePagePath=.%2Fpages%5Capi%5Cgenerate-image.ts&middlewareConfigBase64=e30%3D!:115:13)
    at async DevServer.runApi (C:\cointistreact\node_modules\next\dist\server\next-server.js:766:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\cointistreact\node_modules\next\dist\server\next-server.js:390:37)
    at async DevServer.handleRequestImpl (C:\cointistreact\node_modules\next\dist\server\base-server.js:916:17)
    at async C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:399:20
    at async Span.traceAsyncFn (C:\cointistreact\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:395:24)

2025-09-14T11:47:41.572Z [generate-image] ERROR: This operation was aborted
AbortError: This operation was aborted
    at node:internal/deps/undici/undici:13510:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchWithTimeout (webpack-internal:///(api-node)/./scripts/generate-article-image.js:34:15)
    at async callImagesAPI (webpack-internal:///(api-node)/./scripts/generate-article-image.js:88:15)
    at async generateArticleImage (webpack-internal:///(api-node)/./scripts/generate-article-image.js:555:16)
    at async handler (webpack-internal:///(api-node)/./pages/api/generate-image.ts:346:16)
    at async apiResolver (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:4425)
    at async PagesAPIRouteModule.render (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:5955)
    at async Module.handler (webpack-internal:///(api-node)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fgenerate-image&preferredRegion=&absolutePagePath=.%2Fpages%5Capi%5Cgenerate-image.ts&middlewareConfigBase64=e30%3D!:115:13)
    at async DevServer.runApi (C:\cointistreact\node_modules\next\dist\server\next-server.js:766:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\cointistreact\node_modules\next\dist\server\next-server.js:390:37)
    at async DevServer.handleRequestImpl (C:\cointistreact\node_modules\next\dist\server\base-server.js:916:17)
    at async C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:399:20
    at async Span.traceAsyncFn (C:\cointistreact\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:395:24)

2025-09-14T11:52:57.596Z [generate-image] ERROR: This operation was aborted
AbortError: This operation was aborted
    at node:internal/deps/undici/undici:13510:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchWithTimeout (webpack-internal:///(api-node)/./scripts/generate-article-image.js:44:15)
    at async callImagesAPI (webpack-internal:///(api-node)/./scripts/generate-article-image.js:102:15)
    at async generateArticleImage (webpack-internal:///(api-node)/./scripts/generate-article-image.js:569:16)
    at async handler (webpack-internal:///(api-node)/./pages/api/generate-image.ts:346:16)
    at async apiResolver (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:4425)
    at async PagesAPIRouteModule.render (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:5955)
    at async Module.handler (webpack-internal:///(api-node)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fgenerate-image&preferredRegion=&absolutePagePath=.%2Fpages%5Capi%5Cgenerate-image.ts&middlewareConfigBase64=e30%3D!:115:13)
    at async DevServer.runApi (C:\cointistreact\node_modules\next\dist\server\next-server.js:766:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\cointistreact\node_modules\next\dist\server\next-server.js:390:37)
    at async DevServer.handleRequestImpl (C:\cointistreact\node_modules\next\dist\server\base-server.js:916:17)
    at async C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:399:20
    at async Span.traceAsyncFn (C:\cointistreact\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:395:24)

2025-09-14T11:55:40.506Z [generate-image] ERROR: This operation was aborted
AbortError: This operation was aborted
    at node:internal/deps/undici/undici:13510:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchWithTimeout (webpack-internal:///(api-node)/./scripts/generate-article-image.js:44:15)
    at async callImagesAPI (webpack-internal:///(api-node)/./scripts/generate-article-image.js:102:15)
    at async generateArticleImage (webpack-internal:///(api-node)/./scripts/generate-article-image.js:569:16)
    at async handler (webpack-internal:///(api-node)/./pages/api/generate-image.ts:346:16)
    at async apiResolver (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:4425)
    at async PagesAPIRouteModule.render (C:\cointistreact\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:2:5955)
    at async Module.handler (webpack-internal:///(api-node)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fgenerate-image&preferredRegion=&absolutePagePath=.%2Fpages%5Capi%5Cgenerate-image.ts&middlewareConfigBase64=e30%3D!:115:13)
    at async DevServer.runApi (C:\cointistreact\node_modules\next\dist\server\next-server.js:766:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\cointistreact\node_modules\next\dist\server\next-server.js:390:37)
    at async DevServer.handleRequestImpl (C:\cointistreact\node_modules\next\dist\server\base-server.js:916:17)
    at async C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:399:20
    at async Span.traceAsyncFn (C:\cointistreact\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (C:\cointistreact\node_modules\next\dist\server\dev\next-dev-server.js:395:24)

2025-09-14T17:12:02.608Z [generate-image] ERROR: terminated
TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:11132:53)
    at Fetch.emit (node:events:518:28)
    at Fetch.terminate (node:internal/deps/undici/undici:10290:14)
    at Object.onError (node:internal/deps/undici/undici:11253:38)
    at Request.onError (node:internal/deps/undici/undici:2094:31)
    at Object.errorRequest (node:internal/deps/undici/undici:1591:17)
    at TLSSocket.<anonymous> (node:internal/deps/undici/undici:6319:16)
    at TLSSocket.emit (node:events:530:35)
    at node:net:346:12
    at TCP.done (node:_tls_wrap:650:7)

